cloudprovider: digitalocean
cloudCredentialSecretName: cattle-global-data:cc-prhrv
cluster:
  annotations: {}
  labels:
    cluster_name: do-downstream
  name: do-downstream
kubernetesVersion: v1.25.15+rke2r2
cni: canal
system_default_registry: docker.io
monitoring:
  enabled: false
rke:
  localClusterAuthEndpoint:
    enabled: false
profile: cis-1.23
selinux: true
secrets_encryption: true
protect_kernel_defaults: true
write_kubeconfig_mode: '0640'
use_service_account_credentials: true
kube_apiserver_arg:
  - tls-min-version=VersionTLS12
  - tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - authorization-mode=RBAC,Node
  - anonymous-auth=false
  - audit-policy-file=/etc/rancher/rke2/audit-policy.yaml
  - audit-log-mode=blocking-strict
  - audit-log-maxage=30
  - admission-control-config-file=/etc/rancher/rke2/rancher-pss.yaml
kube_scheduler_arg:
  - tls-min-version=VersionTLS12
  - tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
kube_controller_manager_arg:
  - bind-address=127.0.0.1
  - use-service-account-credentials=true
  - tls-min-version=VersionTLS12
  - tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
kubelet_arg:
  - protect-kernel-defaults=true
  - read-only-port=0
  - authorization-mode=Webhook
  - streaming-connection-idle-timeout=5m

# Specify nodepool options. Can add multiple node groups, specify etcd, controlplane and worker roles.
nodepools:
- etcd: true
  controlplane: true
  worker: false
  labels: {}
  taints: {}
  quantity: 3
  paused: false
  name: control-plane-nodes
  keypairName: 'clemenko'
  #displayName: ""

  # specify machineDeployment Labels
  # machineDeploymentLabels: {}

  # specify machineDeployment annotations
  # machineDeploymentAnnotations: {}

  # specify nodepool name
  name: digitalocean-nodepool-1

  # enable backups for droplet
  # backups: true
  image: rockylinux-9-x64

  # enable ipv6 for droplet
  ipv6: false

  # enable monitoring for droplet
  monitoring: false

  # enable private networking for droplet
  privateNetworking: false

  # Digital Ocean region
  region: nyc3

  # Digital Ocean size
  size: s-4vcpu-8gb-amd

  # File contents for sshKeyContents
  sshKeyContents: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA26evmemRbhTtjV9szD9SwcFW9VOD38jDuJmyYYdqoqIltDkpUqDa/V1jxLSyrizhOHrlJtUOj790cxrvInaBNP7nHIO+GwC9VH8wFi4KG/TFj3K8SfNZ24QoUY12rLiHR6hRxcT4aUGnqFHGv2WTqsW2sxz03z+W1qeMqWYJOUfkqKKs2jiz42U+0Kp9BxsFBlai/WAXrQsYC8CcpQSRKdggOMQf04CqqhXzt5Q4Cmago+Fr7HcvEnPDAaNcVtfS5DYLERcX2OVgWT3RBWhDIjD8vYCMBBCy2QUrc4ZhKZfkF9aemjnKLfLcbdpMfb+r7NwJsVQSPKcjYAJOckE8RQ== clemenko@clemenko.local"

  # SSH key fingerprint
  # sshKeyFingerprint: ""

  # SSH port
  sshPort: 22

  # SSH username
  sshUser: root

  # comma-separated list of tags to apply to the Droplet
  # tags: ""

  # File contents for userdata
  userdata: |
    write_files:
    - path: /etc/sysctl.conf
      owner: root
      content: |
        vm.swappiness=0
        vm.panic_on_oom=0
        vm.overcommit_memory=1
        kernel.panic=10
        kernel.panic_on_oops=1
        vm.max_map_count = 262144
        net.ipv4.ip_local_port_range=1024 65000
        net.core.somaxconn=10000
        net.ipv4.tcp_tw_reuse=1
        net.ipv4.tcp_fin_timeout=15
        net.core.somaxconn=4096
        net.core.netdev_max_backlog=4096
        net.core.rmem_max=16777216
        net.core.wmem_max=16777216
        net.ipv4.tcp_max_syn_backlog=20480
        net.ipv4.tcp_max_tw_buckets=400000
        net.ipv4.tcp_no_metrics_save=1
        net.ipv4.tcp_rmem=4096 87380 16777216
        net.ipv4.tcp_syn_retries=2
        net.ipv4.tcp_synack_retries=2
        net.ipv4.tcp_wmem=4096 65536 16777216
        net.ipv4.neigh.default.gc_thresh1=8096
        net.ipv4.neigh.default.gc_thresh2=12288
        net.ipv4.neigh.default.gc_thresh3=16384
        net.ipv4.tcp_keepalive_time=600
        net.ipv4.ip_forward=1
        net.ipv6.conf.all.disable_ipv6 = 1
        net.ipv6.conf.default.disable_ipv6 = 1
        fs.inotify.max_user_instances=8192
        fs.inotify.max_user_watches=1048576
    - path: /etc/rancher/rke2/audit-policy.yaml
      owner: root
      content: |
        apiVersion: audit.k8s.io/v1
        kind: Policy
        rules:
        - level: RequestResponse
    - path: /etc/rancher/rke2/rancher-pss.yaml
      owner: root
      content: |
        apiVersion: apiserver.config.k8s.io/v1
        kind: AdmissionConfiguration
        plugins:
          - name: PodSecurity
            configuration:
              apiVersion: pod-security.admission.config.k8s.io/v1
              kind: PodSecurityConfiguration
              defaults:
                enforce: "restricted"
                enforce-version: "latest"
                audit: "restricted"
                audit-version: "latest"
                warn: "restricted"
                warn-version: "latest"
              exemptions:
                usernames: []
                runtimeClasses: []
                namespaces: [calico-apiserver,
                            calico-system,
                            carbide-docs-system,
                            carbide-stigatron-system,
                            cattle-alerting,
                            cattle-csp-adapter-system,
                            cattle-elemental-system,
                            cattle-epinio-system,
                            cattle-externalip-system,
                            cattle-fleet-local-system,
                            cattle-fleet-system,
                            cattle-gatekeeper-system,
                            cattle-global-data,
                            cattle-global-nt,
                            cattle-impersonation-system,
                            cattle-istio,
                            cattle-istio-system,
                            cattle-logging,
                            cattle-logging-system,
                            cattle-monitoring-system,
                            cattle-neuvector-system,
                            cattle-prometheus,
                            cattle-provisioning-capi-system,
                            cattle-resources-system,
                            cattle-sriov-system,
                            cattle-system,
                            cattle-ui-plugin-system,
                            cattle-windows-gmsa-system,
                            cert-manager,
                            cis-operator-system,
                            fleet-default,
                            fleet-local,
                            ingress-nginx,
                            istio-system,
                            kube-node-lease,
                            kube-public,
                            kube-system,
                            longhorn-system,
                            rancher-alerting-drivers,
                            security-scan,
                            tigera-operator]
    runcmd:
    - sudo sysctl -p > /dev/null 2>&1
    - sudo yum install -y iptables container-selinux iptables libnetfilter_conntrack libnfnetlink libnftnl policycoreutils-python-utils cryptsetup nfs-utils iscsi-initiator-utils zip zstd tree jq
    - sudo curl -#OL https://github.com/rancher/rke2-selinux/releases/download/v0.16.stable.1/rke2-selinux-0.16-1.el9.noarch.rpm && sudo rpm -i rke2-selinux-0.16-1.el9.noarch.rpm
    - sudo echo "InitiatorName=$(/sbin/iscsi-iname)" > /etc/iscsi/initiatorname.iscsi && systemctl enable --now iscsid
    - sudo systemctl stop firewalld; systemctl disable firewalld; systemctl stop nm-cloud-setup; systemctl disable nm-cloud-setup; systemctl stop nm-cloud-setup.timer; systemctl disable nm-cloud-setup.timer
    - sudo echo -e "[keyfile]\nunmanaged-devices=interface-name:cali*;interface-name:flannel*" > /etc/NetworkManager/conf.d/rke2-canal.conf
    - sudo mkdir -p /opt/rke2-artifacts/ /etc/rancher/rke2/ /var/lib/rancher/rke2/server/manifests/
    - sudo useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U
