kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: flask
  namespace: fleet-local
spec:
  repo: https://github.com/clemenko/fleet
  targetNamespace: flask
  paths:
  - flask_simple.yaml
